### ISSUE TITLE
Support Twitch

### ISSUE THREAD

**Issue by jmworks** [nolaneo/vemos#22]
Hi, thanks for the great work.

Do you have plan to support twitch? 
It would be nice if you support it.

**Comment by nolaneo** [comment]
It seems to (kind of) work with the new release! This is currently being reviewed by Google before being released but hopefully it's out soon.

Live content is a bit hard to sync because the seek action doesn't work exactly. I can take a look to see how this could be made better.

**Comment by nolaneo** [comment]
v 0.0.5 is now available on the Chrome store if you want to try it out with Twitch

**Comment by jmworks** [comment]
It works!! Thank you so much!
