### ISSUE TITLE
Support for Crave?

### ISSUE THREAD

**Issue by grantbowering** [nolaneo/vemos#23]
While we're talking about adding media providers to this extension: 

[Crave](https://www.crave.ca) is the Canadian streaming provider for HBO, Cinemax, Showtime, and a bunch of other stuff.  I use it as daily as I do netflix and prime video...

I know that might be hard to do for non-Canadians, and I'm a dev (never used ember but lots of experience with react and angular) so I can take point on it, if you're okay with it existing?

**Comment by grantbowering** [comment]
Update:

I tried to get this working now that master has the new permissions strategy from PR #21...  

The good news is that the console does log play, pause, and seek behavior on the video window, so in theory the extension should be supported.

The bad news is that the session doesn't start.
I do initially get the following console output:
```
Setting vemos peer id
Adding Vemos message listener
VEMOS URL ALREADY INITIALIZED
VEMOS CONTENT ALREADY INITIALIZED
A Peer ID was present, booting Vemos
```
But when the site loads, the Vemos sidebar doesn't appear, and clicking the Vemos button on the toolbar just gives a "Start Watching Together!" dialog.

I'm guessing that this is because Crave is stripping unrecognized querystring items out of the URL, because the `vemos-id` disappears from the address when the site loads.

Any thoughts on preventing that from happening, or an alternative way to access the session?

**Comment by grantbowering** [comment]
(...oh.  As a sanity check, I went back and tried Amazon Prime Video again, which is not working in 0.0.5 either.  So I guess it's not ready as of this commit then, sorry for being premature 😆)

**Comment by nolaneo** [comment]
Thanks @grantbowering, this is a bug with the `vemos.org/connect` page which I'm taking a look at now! Sorry if you spent time trying to figure this out, I didn't realise anyone was looking at it! 🙈

**Comment by nolaneo** [comment]
![image](https://user-images.githubusercontent.com/2514088/79260196-cb03de80-7e85-11ea-8cbc-1ed10e3f0dc3.png)

I can't actually access the videos since I'm not in 🇨🇦, but I can at least connect to an invite link to crave.ca. I'm not sure if this hints at your issue also being fixed by the fix to vemos.org/connect.

**Comment by nolaneo** [comment]
v 0.0.5 is now available on the Chrome store which lets you opt into any site if you want to try it out.

**Comment by grantbowering** [comment]
hmm... I'm not currently having any luck with official.  I'll try it in developer mode with master later today

**Comment by grantbowering** [comment]
So, I tried to use it a couple days ago with a friend, and it was pretty painful, it did eventually work but it took like ten tries of doing the same thing over and over before I managed to see my friend AND the video at the same time...  
The problems that I had are: 
 1. Crave often ends up triggering a refresh of the page before it starts playing, which causes the peer id to be lost.  What I eventually succeeded at was pasting `&vemos-id={whatever}` back into the address bar until it stayed set.  When Crave does this refresh, it doesn't result in clearing querystring params; the reason the vemos-id disappears is because vemos deletes it from the url once it detects it's been set as `window.VEMOS_PEER_ID`.  Is there a reason we can't just keep the vemos-id in the querystring?  As far as I can see, its presence is no longer used as the input to an if-else, so why bother removing it at all?  I think that if we leave it there, if the window refreshes then `window.VEMOS_URL_SET` won't be set anymore and I think it'll just work...
 2. Sometimes the video element doesn't appear on the page within a reasonable time frame, Because Reasons.  When that happens, vemos doesn't find anything to bind to, and it doesn't ever check again...  perhaps, if there are no video elements present, it could setTimeout to look again in like ten seconds?  Just a thought 🤷‍♂️
 3. Even on the try that it finally worked, vemos didn't come up automatically; I had to click the Vemos button on the toolbar and the "Start watching together!" button but then my friend did appear in the resulting session.  I have no idea what caused that, some combination of 1 and 2 perhaps...

**Comment by nolaneo** [comment]
Thanks for the really detailed writeup @grantbowering 🙇 

To answer some of these:
> Is there a reason we can't just keep the vemos-id in the querystring? As far as I can see, its presence is no longer used as the input to an if-else, so why bother removing it at all?

I found that people would often refresh the page, or go back to that link again in their browser history which would confusing cause Vemos to boot which was very confusing so I removed the query param on load. I'm going to fix this by using the background script to provide the Vemos ID rather than the query param. https://github.com/nolaneo/vemos/pull/27

> if there are no video elements present, it could setTimeout to look again in like ten seconds?
Gah! I'd added a MutationObserver to check for if the video element _changes_ and update the reference, but not one for when it's not found at all. I'll fix that up!

**Comment by nolaneo** [comment]
I've submitted those changes to the Chrome store. (v0.0.6)
I've also added the ability to manually copy/paste a code to make cases like you described a bit easier:
![manual connection](https://user-images.githubusercontent.com/2514088/79640979-b3ca3700-818c-11ea-8352-7092c2a8f7b4.gif)

**Comment by grantbowering** [comment]
FYI, I tried 0.0.7 last night and it worked beautifully.  Thank you for all your hard work!! ❤
