### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by wadefletch** [nolaneo/vemos#24]
Hello! I'd love to contribute to this project, please let me know where I can help! Thanks!

**Comment by nolaneo** [comment]
Hey @wadefletch, thanks for the offer!

One thing I'd love some help with is getting it working a bit better with Hulu https://github.com/nolaneo/vemos/issues/16. I can't get an account in Europe so it makes testing and debugging quite hard.

In particular, I've heard there's problems especially when ads play (that's not handled at all).
