### ISSUE TITLE
there is no audio without video

### ISSUE THREAD

**Issue by grantbowering** [nolaneo/vemos#47]
When I connect with a friend who has a microphone but not a camera, on her end she appears as a black square and she can see my video and hear my audio, but on my end I see no indication of her presence other than the onPeerCall event having fired in the console.  I can't hear her audio at all, nor do I see an empty black camera window.  
Also, when I turn off my camera by using the "Disable your webcam" button, she can no longer hear my microphone either, though the microphone is not muted.  I suspect these problems may be related.
(Version 0.1.0)

**Comment by nolaneo** [comment]
Thanks @grantbowering I'll take a look.

**Comment by nolaneo** [comment]
Closed via https://github.com/nolaneo/vemos/pull/48

These fixes are included in v0.1.2 which I'm submitting to Google now.
Cheers for the report as always! 🙂
